### ISSUE TITLE
Loko Base Software up to date?

### ISSUE THREAD

**Issue by Tropaion** [tomipiriyev/Loko#12]
Hello @tomipiriyev,
I wanted to ask, is the python script for the loko base really the latest one?
There are many things missing or incorrect. For example the gpio for driving the led is incorrect and rgb isn't used either.
Also the adc part for the battery is commented + some additional areas.
Would it be possible to provide the latest version?
Thank you.

**Comment by tomipiriyev** [comment]
Hi @Tropaion 
I updated with new firmware. 
also after saving new firmware , run it , then reconnect you will see that new  .Jason  file created inside ESP32 . inside that file you can change ID and frequency 

after running the code, then you can disconnect the cable . 
<img width="1515" alt="Screenshot 2023-12-10 at 21 14 20" src="https://github.com/tomipiriyev/Loko/assets/8874891/40bb5372-525f-43fd-af47-db29ea2708d0">
