### ISSUE TITLE
How to configure Loko without Mac?

### ISSUE THREAD

**Issue by Tropaion** [tomipiriyev/Loko#13]
Hello @tomipiriyev,
is there a way to configure Loko without an Mac?
I tried creating a VM with MacOS to run it, but sadly it doesn't work.
![image](https://github.com/tomipiriyev/Loko/assets/6797663/4d4945cb-7418-4769-a443-2e666f52f759)

**Comment by tomipiriyev** [comment]
Hi @Tropaion ,

have you tried Loko configuration tool for Win ? (https://nolilab.com/pages/software)
