### ISSUE TITLE
Loko Air LoRa antenna

### ISSUE THREAD

**Issue by tyagodani** [tomipiriyev/Loko#9]
In the pictures published, I've seen at least two different lengths of antennas being used. What would you adivse to use?
Also, wouldn't it be possible to use an internal coil antenna or even a cermic loop one?
Cheers

**Comment by tomipiriyev** [comment]
@tyagodani We use 0.6mm diameter silver wire ( sterling 925) .  coil antenna and ceramic antenna will not work good,   on PCB there is GPS antenna and it has height.  it would block the ceramic antenna radiation patter .

**Comment by tyagodani** [comment]
Thank you Tomi. Cheers

**Comment by tyagodani** [comment]
@tomipiriyev where did you source the wire from?

**Comment by tomipiriyev** [comment]
@tyagodani I sourced from local stores. they usually use in silver jewellers.   But you can use copper wire as well . 
Litz wire search ,   "0.07 x 28 Litz wire" , search like this , it will work fine too, it is widely used wire

**Comment by tyagodani** [comment]
@tomipiriyev so this is the same as enamel or magnet wire? does it have to be specifically 0.07 x 28 or can be something close? i'm having trouble finding those specs

**Comment by tomipiriyev** [comment]
@tyagodani  doesn't have to be specifically 0.07 x 28 ,   it is just I tried , it has good flexibility and diameter can fit to the hole on pcb to solder ,  you can buy any size close to this size

**Comment by tyagodani** [comment]
Thank you @tomipiriyev!

I ordered the following from Mouser, for future reference, in case anyone wants to try. Got a couple different ones. I will post an update once they arrive on what I find to be best:
https://eu.mouser.com/ProductDetail/TE-Connectivity-Raychem/82A0111-26-9?qs=pLY5GE0xrmKpOKZDA%2FxY%2FQ%3D%3D
https://eu.mouser.com/ProductDetail/TE-Connectivity-Raychem/C39461-000?qs=P1JMDcb91o63NRRgTrYKmg%3D%3D

**Comment by tomipiriyev** [comment]
@tyagodani  anywise will work

**Comment by crazybanane** [comment]
can someone take a  photo how the antenna wire is connected on the board?

**Comment by tyagodani** [comment]
@crazybanane here you go

![Image](https://github.com/user-attachments/assets/cf0ab6ac-2300-448b-bf82-d5e172a03464)
